/*
 *	IngeScape Common
 *
 *  Copyright © 2019 Ingenuity i/o. All rights reserved.
 *
 *	See license terms for the rights and conditions
 *	defined by copyright holders.
 *
 *
 *	Contributors:
 *      Alexandre Lemort   <lemort@ingenuity.io>
 *
 */

#include "linuxutils.h"



#ifdef Q_OS_LINUX

//---------------------------------------------------------------------
//
//
//  Linux API
//
//
//---------------------------------------------------------------------

#include <QDBusConnection>
#include <QDBusInterface>

#include <QDebug>


//
// Define our singleton instance
//
Q_GLOBAL_STATIC(LinuxUtils, _singletonInstance)


/**
 * @brief Constructor
 * @param parent
 */
LinuxUtils::LinuxUtils(QObject *parent)
    : OSUtils(parent)
{
    // Check if UPower is available
    if (
        (QDBusConnection::systemBus().interface() != nullptr)
        &&
        QDBusConnection::systemBus().interface()->isServiceRegistered( UPowerService )
        )
    {
        // Subscribe to UPower
        QDBusConnection dbusConnection = QDBusConnection::systemBus();
        dbusConnection.connect("org.freedesktop.UPower", "/org/freedesktop/UPower", "org.freedesktop.UPower", "Sleeping", this, SLOT(_onUPowerSleeping()));
        dbusConnection.connect("org.freedesktop.UPower", "/org/freedesktop/UPower", "org.freedesktop.UPower", "Resuming", this, SLOT(_onUPowerResuming()));
    }
    else
    {
        qWarning() << Q_FUNC_INFO << ": UPower is not available";
    }
}


/**
 * @brief Destructor
 */
LinuxUtils::~LinuxUtils()
{
}


/**
 * @brief Get our singleton instance
 * @return
 */
LinuxUtils* LinuxUtils::instance()
{
    return _singletonInstance;
}


/**
 * @brief Remove all menu items generated by Qt to handle conventions
 */
void LinuxUtils::removeOSGeneratedMenuItems()
{
}


/**
 * @brief Enable energy efficiency features
 */
void LinuxUtils::_enableEnergyEfficiencyFeatures()
{
}


/**
 * @brief Disable energy efficiency features
 */
void LinuxUtils::_disableEnergyEfficiencyFeatures()
{
}


/**
 * @brief Triggered when we receive a Sleeping signal from DBUS
 */
void LinuxUtils::_onUPowerSleeping()
{
    Q_EMIT systemSleep();
}


/**
 * @brief Triggered when we receive a Resume signal from DBUS
 */
void LinuxUtils::_onUPowerResuming()
{
    Q_EMIT systemWake();
}



#else

//---------------------------------------------------------------------
//
//  Fake API to avoid compiler errors (empty source file)
//
//---------------------------------------------------------------------

/**
 * @brief Constructor
 * @param parent
 */
LinuxUtils::LinuxUtils(QObject *parent)
    : OSUtils(parent)
{
}

#endif
