COPY ingescape.record TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-record.csv' with header=true;

COPY ingescape.event TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-event.csv' with header=true;
COPY ingescape.int TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-int.csv' with header=true;
COPY ingescape.double TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-double.csv' with header=true;
COPY ingescape.string TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-string.csv' with header=true;
COPY ingescape.bool TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-bool.csv' with header=true;
COPY ingescape.data TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-data.csv' with header=true;
COPY ingescape.action TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-action.csv' with header=true;
COPY ingescape.mapping TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-mapping.csv' with header=true;
COPY ingescape.timeline TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-timeline.csv' with header=true;

COPY ingescape.experimentation TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-experimentation.csv' with header=true;
COPY ingescape.characteristic TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-characteristic.csv' with header=true;
COPY ingescape.subject TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-subject.csv' with header=true;
COPY ingescape.protocol TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-protocol.csv' with header=true;
COPY ingescape.independent_var TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-independent_var.csv' with header=true;
COPY ingescape.dependent_var TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-dependent_var.csv' with header=true;
COPY ingescape.characteristic_value TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-characteristic_value.csv' with header=true;
COPY ingescape.session TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-session.csv' with header=true;
COPY ingescape.independent_var_value TO '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-independent_var_value.csv' with header=true;
