COPY ingescape.record FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-record.csv' with header=true;

COPY ingescape.event FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-event.csv' with header=true;
COPY ingescape.int FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-int.csv' with header=true;
COPY ingescape.double FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-double.csv' with header=true;
COPY ingescape.string FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-string.csv' with header=true;
COPY ingescape.bool FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-bool.csv' with header=true;
COPY ingescape.data FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-data.csv' with header=true;
COPY ingescape.action FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-action.csv' with header=true;
COPY ingescape.mapping FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-mapping.csv' with header=true;
COPY ingescape.timeline FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-timeline.csv' with header=true;

COPY ingescape.experimentation FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-experimentation.csv' with header=true;
COPY ingescape.characteristic FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-characteristic.csv' with header=true;
COPY ingescape.subject FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-subject.csv' with header=true;
COPY ingescape.protocol FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-protocol.csv' with header=true;
COPY ingescape.independent_var FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-independent_var.csv' with header=true;
COPY ingescape.dependent_var FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-dependent_var.csv' with header=true;
COPY ingescape.characteristic_value FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-characteristic_value.csv' with header=true;
COPY ingescape.session FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-session.csv' with header=true;
COPY ingescape.independent_var_value FROM '/Users/Vincent/Travail/Ingenuity_io/IngeScape/Assessments/export-eval-multimodale/ingescape-independent_var_value.csv' with header=true;
