# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.18)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget sodium sodium-static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target sodium
add_library(sodium SHARED IMPORTED)

set_target_properties(sodium PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Admin/Documents/DEV/work/ingescape/dependencies/sodium/src/libsodium/include;C:/Users/Admin/Documents/DEV/work/ingescape/dependencies/sodium/src/libsodium/include/sodium"
)

# Create imported target sodium-static
add_library(sodium-static STATIC IMPORTED)

set_target_properties(sodium-static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SODIUM_STATIC"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Admin/Documents/DEV/work/ingescape/dependencies/sodium/src/libsodium/include;C:/Users/Admin/Documents/DEV/work/ingescape/dependencies/sodium/src/libsodium/include/sodium"
)

# Import target "sodium" for configuration "Debug"
set_property(TARGET sodium APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(sodium PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/Admin/Documents/DEV/work/ingescape/builds/visual-studio/dependencies/x64/dependencies/sodium/Debug/sodium.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/Admin/Documents/DEV/work/ingescape/builds/visual-studio/dependencies/x64/dependencies/sodium/Debug/libsodium.dll"
  )

# Import target "sodium-static" for configuration "Debug"
set_property(TARGET sodium-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(sodium-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/Users/Admin/Documents/DEV/work/ingescape/builds/visual-studio/dependencies/x64/dependencies/sodium/Debug/libsodium.lib"
  )

# Import target "sodium" for configuration "Release"
set_property(TARGET sodium APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(sodium PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/Admin/Documents/DEV/work/ingescape/builds/visual-studio/dependencies/x64/dependencies/sodium/Release/sodium.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/Admin/Documents/DEV/work/ingescape/builds/visual-studio/dependencies/x64/dependencies/sodium/Release/libsodium.dll"
  )

# Import target "sodium-static" for configuration "Release"
set_property(TARGET sodium-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(sodium-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/Users/Admin/Documents/DEV/work/ingescape/builds/visual-studio/dependencies/x64/dependencies/sodium/Release/libsodium.lib"
  )

# Import target "sodium" for configuration "MinSizeRel"
set_property(TARGET sodium APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(sodium PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/Admin/Documents/DEV/work/ingescape/builds/visual-studio/dependencies/x64/dependencies/sodium/MinSizeRel/sodium.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Admin/Documents/DEV/work/ingescape/builds/visual-studio/dependencies/x64/dependencies/sodium/MinSizeRel/libsodium.dll"
  )

# Import target "sodium-static" for configuration "MinSizeRel"
set_property(TARGET sodium-static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(sodium-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Admin/Documents/DEV/work/ingescape/builds/visual-studio/dependencies/x64/dependencies/sodium/MinSizeRel/libsodium.lib"
  )

# Import target "sodium" for configuration "RelWithDebInfo"
set_property(TARGET sodium APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(sodium PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/Admin/Documents/DEV/work/ingescape/builds/visual-studio/dependencies/x64/dependencies/sodium/RelWithDebInfo/sodium.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Admin/Documents/DEV/work/ingescape/builds/visual-studio/dependencies/x64/dependencies/sodium/RelWithDebInfo/libsodium.dll"
  )

# Import target "sodium-static" for configuration "RelWithDebInfo"
set_property(TARGET sodium-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(sodium-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Admin/Documents/DEV/work/ingescape/builds/visual-studio/dependencies/x64/dependencies/sodium/RelWithDebInfo/libsodium.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
