/*
 *	IngeScape Common
 *
 *  Copyright © 2019 Ingenuity i/o. All rights reserved.
 *
 *	See license terms for the rights and conditions
 *	defined by copyright holders.
 *
 *
 *	Contributors:
 *      Alexandre Lemort   <lemort@ingenuity.io>
 *
 */

#include "linuxutils.h"



#ifdef Q_OS_LINUX

//---------------------------------------------------------------------
//
//
//  Linux API
//
//
//---------------------------------------------------------------------

//
// Define our singleton instance
//
Q_GLOBAL_STATIC(LinuxUtils, _singletonInstance)


/**
 * @brief Constructor
 * @param parent
 */
LinuxUtils::LinuxUtils(QObject *parent)
    : OSUtils(parent)
{
}


/**
 * @brief Destructor
 */
LinuxUtils::~LinuxUtils()
{
}


/**
 * @brief Get our singleton instance
 * @return
 */
LinuxUtils* LinuxUtils::instance()
{
    return _singletonInstance;
}


/**
 * @brief Remove all menu items generated by Qt to handle conventions
 */
void LinuxUtils::removeOSGeneratedMenuItems()
{
}


/**
 * @brief Enable energy efficiency features
 */
void LinuxUtils::_enableEnergyEfficiencyFeatures()
{
}


/**
 * @brief Disable energy efficiency features
 */
void LinuxUtils::_disableEnergyEfficiencyFeatures()
{
}



#else

//---------------------------------------------------------------------
//
//  Fake API to avoid compiler errors (empty source file)
//
//---------------------------------------------------------------------

/**
 * @brief Constructor
 * @param parent
 */
LinuxUtils::LinuxUtils(QObject *parent)
    : OSUtils(parent)
{
}

#endif
