/*
 *	IngeScape Common
 *
 *  Copyright © 2019 Ingenuity i/o. All rights reserved.
 *
 *	See license terms for the rights and conditions
 *	defined by copyright holders.
 *
 *
 *	Contributors:
 *      Alexandre Lemort   <lemort@ingenuity.io>
 *
 */

#ifndef MACOSUTILS_H
#define MACOSUTILS_H

#include <QtGlobal>
#include <QObject>
#include <QScopedPointer>




#ifndef Q_OS_MAC
//
// Non-macos definition
//
class MacosUtils
{
public:
    /**
     * @brief Constructor
     */
     MacosUtils() {}
};


#else
//
// Macos definition
//

class MacosUtilsPrivate;


/**
 * @brief The MacosUtils class defines a set of utility functions to perform macos specific operations
 */
class MacosUtils : public QObject
{
    Q_OBJECT


public:
    /**
     * @brief Constructor
     */
     explicit MacosUtils(QObject *parent = nullptr);


     /**
      * @brief Destructor
      */
     ~MacosUtils();


     /**
      * @brief Get our singleton instance
      * @return
      */
     static MacosUtils& instance();


     /**
      * @brief Init
      */
     void init();


     /**
      * @brief Clean
      */
     void clean();


    /**
     * @brief Remove all menu items generated by Qt to handle conventions
     */
    void removeOSGeneratedMenuItems();


    /**
     * @brief Enable or disable energy efficiency features
     *
     * @param value
     */
    void energyEfficiencyFeaturesEnabled(bool value);


Q_SIGNALS:
    /**
     * @brief Triggered when our machine will go to sleep
     */
    void systemSleep();


    /**
     * @ brief Triggered when our machine did wake from sleep
     */
    void systemWake();


protected:
    /**
     * @brief Subscribe to system power notifications (sleep, wake)
     */
    void _subscribeToSystemPowerNotifications();


    /**
     * @brief Remove the "Start Dictation..." menu item from the "Edit" menu
     */
    void _removeMenuItemStartDictation();


    /**
     * @brief Remove the "Emoji & Symbols" menu item from the "Edit" menu
     */
    void _removeMenuItemEmojiAndSymbols();


protected:
    QScopedPointer<MacosUtilsPrivate> _privateAPI;
};

#endif


#endif // MACOSUTILS_H
