/*
 *	IngeScape Common
 *
 *  Copyright © 2019 Ingenuity i/o. All rights reserved.
 *
 *	See license terms for the rights and conditions
 *	defined by copyright holders.
 *
 *
 *	Contributors:
 *      Alexandre Lemort   <lemort@ingenuity.io>
 *
 */

#ifndef MACOSUTILS_H
#define MACOSUTILS_H

#include <QtGlobal>


/**
 * @brief The MacosUtils class defines a set of utility functions to perform macos specific operations
 */
class MacosUtils
{
public:
    /**
     * @brief Constructor
     */
     MacosUtils() {}


    //---------------------------------
    //
    // Macos specific methods
    //
    //---------------------------------
#ifdef Q_OS_MAC

    /**
     * @brief Remove all menu items generated by Qt to handle conventions
     */
    static void removeMacosGeneratedMenuItems();


    /**
     * @brief Remove the "Start Dictation..." menu item from the "Edit" menu
     */
    static void removeMenuItemStartDictation();


    /**
     * @brief Remove the "Emoji & Symbols" menu item from the "Edit" menu
     */
    static void removeMenuItemEmojiAndSymbols();

#endif

};

#endif // MACOSUTILS_H
