/*
 *	IngeScape Common
 *
 *  Copyright © 2019 Ingenuity i/o. All rights reserved.
 *
 *	See license terms for the rights and conditions
 *	defined by copyright holders.
 *
 *
 *	Contributors:
 *      Alexandre Lemort   <lemort@ingenuity.io>
 *
 */

#ifndef MACOSUTILS_H
#define MACOSUTILS_H

#include <QtGlobal>
#include <QObject>
#include <QScopedPointer>

#include "osutils.h"


#ifdef Q_OS_MAC
//
// Macos definition
//

class MacosUtilsPrivate;


/**
 * @brief The MacosUtils class defines a set of utility functions to perform macos specific operations
 */
class MacosUtils : public OSUtils
{
    Q_OBJECT


public:
    /**
     * @brief Constructor
     */
     explicit MacosUtils(QObject *parent = nullptr);


     /**
      * @brief Destructor
      */
     ~MacosUtils() Q_DECL_OVERRIDE;


     /**
      * @brief Get our singleton instance
      * @return
      */
     static MacosUtils* instance();


     /**
      * @brief Remove all menu items generated by Qt to handle conventions
      */
     void removeOSGeneratedMenuItems() Q_DECL_OVERRIDE;



protected:
    /**
     * @brief Enable energy efficiency features
     */
    void _enableEnergyEfficiencyFeatures() Q_DECL_OVERRIDE;


    /**
     * @brief Disable energy efficiency features
     */
    void _disableEnergyEfficiencyFeatures() Q_DECL_OVERRIDE;


    /**
     * @brief Remove the "Start Dictation..." menu item from the "Edit" menu
     */
    void _removeMenuItemStartDictation();


    /**
     * @brief Remove the "Emoji & Symbols" menu item from the "Edit" menu
     */
    void _removeMenuItemEmojiAndSymbols();


protected:
    QScopedPointer<MacosUtilsPrivate> _privateAPI;
};


#else

//
// Non-macos definition
//
class MacosUtils : public OSUtils
{
public:
    /**
     * @brief Constructor
     */
     explicit MacosUtils(QObject* parent = nullptr) : OSUtils(parent) {}
};


#endif


#endif // MACOSUTILS_H
