/*
 *	IngeScape Common
 *
 *  Copyright © 2019 Ingenuity i/o. All rights reserved.
 *
 *	See license terms for the rights and conditions
 *	defined by copyright holders.
 *
 *
 *	Contributors:
 *      Alexandre Lemort   <lemort@ingenuity.io>
 *
 */


#include "macosutils.h"

#import <Foundation/Foundation.h>


/**
 * @brief Remove all menu items generated by Qt to handle conventions
 */
void MacosUtils::removeMacosGeneratedMenuItems()
{
    // Clean-up our Edit menu
    removeMenuItemStartDictation();
    removeMenuItemEmojiAndSymbols();
}


/**
 * @brief Remove the "Start Dictation..." menu item from the "Edit" menu
 */
void MacosUtils::removeMenuItemStartDictation()
{
    [[NSUserDefaults standardUserDefaults] setBool:YES forKey:@"NSDisabledDictationMenuItem"];
}


/**
 * @brief Remove the "Emoji & Symbols" menu item from the "Edit" menu
 */
void MacosUtils::removeMenuItemEmojiAndSymbols()
{
    [[NSUserDefaults standardUserDefaults] setBool:YES forKey:@"NSDisabledCharacterPaletteMenuItem"];
}

