/*
 *	IngeScape Common
 *
 *  Copyright © 2019 Ingenuity i/o. All rights reserved.
 *
 *	See license terms for the rights and conditions
 *	defined by copyright holders.
 *
 *
 *	Contributors:
 *      Alexandre Lemort   <lemort@ingenuity.io>
 *
 */

#include "microsoftwindowutils.h"

#include <QDebug>


#ifdef Q_OS_WIN

#include <windows.h>

//---------------------------------------------------------------------
//
//
//  Microsoft Window API
//
//
//---------------------------------------------------------------------

/**
 * @brief Constructor
 */
MicrosoftWindowUtilsEventFilter::MicrosoftWindowUtilsEventFilter()
{
}


/**
 * @brief This method is called for every native event
 * @param eventType
 * @param message
 * @param result
 * @return
 */
bool MicrosoftWindowUtilsEventFilter::nativeEventFilter(const QByteArray &eventType, void *message, long *result)
{
    Q_UNUSED(message)
    Q_UNUSED(result)

    //TODO: check if we also need "windows_dispatcher_MSG" (system-wide messages)
    if (eventType == "windows_generic_MSG")
    {
        MSG* msg = static_cast<MSG*>(message);
        if (msg != nullptr)
        {
            // Check if we have a system power notification
            if (msg->message == WM_POWERBROADCAST)
            {
                // See https://docs.microsoft.com/en-us/windows/win32/power/wm-powerbroadcast

                if (msg->wParam == PBT_APMRESUMEAUTOMATIC)
                {
                    if (MicrosoftWindowUtils::instance() != nullptr)
                    {
                        MicrosoftWindowUtils::instance()->systemWake();
                    }
                }
                else if (msg->wParam == PBT_APMSUSPEND)
                {
                    if (MicrosoftWindowUtils::instance() != nullptr)
                    {
                        MicrosoftWindowUtils::instance()->systemSleep();
                    }
                }
            }
        }
    }

    // No filter
    return false;
}



//
// Define our singleton instance
//
Q_GLOBAL_STATIC(MicrosoftWindowUtils, _singletonInstance)


/**
 * @brief Constructor
 * @param parent
 */
MicrosoftWindowUtils::MicrosoftWindowUtils(QObject *parent)
    : OSUtils(parent),
      _eventFilter(nullptr)
{
    // Subscribe to currentWindow changes
    connect(this, &MicrosoftWindowUtils::currentWindowChanged, this, &MicrosoftWindowUtils::_onCurrentWindowChanged);

    // Try to install our event filter
    if (QCoreApplication::instance() != nullptr)
    {
        _eventFilter = new MicrosoftWindowUtilsEventFilter();
        QCoreApplication::instance()->installNativeEventFilter(_eventFilter);
    }
}


/**
 * @brief Destructor
 */
MicrosoftWindowUtils::~MicrosoftWindowUtils()
{
    // Unsubscribe to currentWindow changes
    disconnect(this, &MicrosoftWindowUtils::currentWindowChanged, this, &MicrosoftWindowUtils::_onCurrentWindowChanged);


    // Clean-up our event filter
    if (_eventFilter != nullptr)
    {
        if (QCoreApplication::instance() != nullptr)
        {
            QCoreApplication::instance()->removeNativeEventFilter(_eventFilter);
        }
        // Else: should not happen because we can not create an event filter without a QCoreApplication

        delete _eventFilter;
        _eventFilter = nullptr;
    }    
}


/**
 * @brief Get our singleton instance
 * @return
 */
MicrosoftWindowUtils* MicrosoftWindowUtils::instance()
{
    return _singletonInstance;
}


/**
 * @brief Remove all menu items generated by Qt to handle conventions
 */
void MicrosoftWindowUtils::removeOSGeneratedMenuItems()
{
    // Nothing to do: Qt does not add extra menu items on Windows
}


/**
 * @brief Called when our currentWindow property has changed
 */
void MicrosoftWindowUtils::_onCurrentWindowChanged()
{

}


/**
 * @brief Enable energy efficiency features
 */
void MicrosoftWindowUtils::_enableEnergyEfficiencyFeatures()
{
}


/**
 * @brief Disable energy efficiency features
 */
void MicrosoftWindowUtils::_disableEnergyEfficiencyFeatures()
{
}



#else

//---------------------------------------------------------------------
//
//  Fake API to avoid compiler errors (empty source file)
//
//---------------------------------------------------------------------

/**
 * @brief Constructor
 * @param parent
 */
MicrosoftWindowUtils::MicrosoftWindowUtils(QObject *parent)
    : OSUtils(parent)
{
}


#endif

