//  Generated by configure.bat
 
#ifndef __PLATFORM_H_INCLUDED__
#define __PLATFORM_H_INCLUDED__
 
#define ZYRE_HAVE_WINDOWS 
#define HAVE_LIBZMQ 
#undef HAVE_UUID
#define HAVE_CZMQ 
//  Provide draft classes and methods
#define ZYRE_BUILD_DRAFT_API 
 
#endif
